name: X AI Auto Post

on:
  schedule:
    # 毎日 9時（JST） = 0時（UTC）
    - cron: '0 0 * * *'
    # 毎日 12時（JST） = 3時（UTC）
    - cron: '0 3 * * *'
    # 毎日 18時（JST） = 9時（UTC）
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行を許可

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy openai
    
    - name: Run auto post script
      env:
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python x_ai_smart_post.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: post-logs
        path: x_ai_smart_post.log
        retention-days: 30

